In [1]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('books.csv')

In [101]:
data.shape

(5000, 10)

In [104]:
datatype(df)

NameError: name 'datatype' is not defined

In [102]:
books_data = pd.read_csv[{"title": "average_rating"}]

TypeError: 'function' object is not subscriptable

In [7]:
print(books_data)

[{'title': 'average_rating'}]

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               5000 non-null   object
 1   author              5000 non-null   object
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64
 4   language_code       4923 non-null   object
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64
 7   text_reviews_count  5000 non-null   int64
 8   publisher           5000 non-null   object
 9   year                5000 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB

In [18]:
df['average_rating'] = df.iloc[:,1:].mean(axis=1)

TypeError: can only concatenate str (not "float") to str

In [19]:
df

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006
...,...,...,...,...,...,...,...,...,...,...
4995,The Complete Works,Michel de Montaigne,4.44,9781400040216,eng,1392.0,166,13,Everyman's Library,2003
4996,Shipwreck (Island I),Gordon Korman,3.80,9780439023313,eng,NaN,103,14,Scholastic Audio Books,2007
4997,Every Night Italian: Every Night Italian,Giuliano Hazan,3.79,9780684800288,eng,256.0,70,2,Scribner,2000
4998,Go Down Moses,William Faulkner,3.93,9780679732174,eng,365.0,8289,370,Vintage,1991
4999,The Avignon Quintet: Monsieur Livia Constanc...,Lawrence Durrell,4.07,9780571225552,en-US,1376.0,287,23,Faber & Faber,2004

In [20]:
high_rated_books = df[df['average_rating']>4]

In [21]:
high_rated_books

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006
5,The Hand of Chaos (The Death Gate Cycle #5),Margaret Weis,4.06,9780553563696,eng,446.0,16301,117,Spectra,1993
6,On Intelligence,Jeff Hawkins,4.12,9780805078534,eng,261.0,5347,396,St. Martin's Griffin,2005
11,Merlin's Tour of the Universe,Neil deGrasse Tyson,4.02,9780385488358,eng,318.0,305,27,Main Street Books,1997
...,...,...,...,...,...,...,...,...,...,...
4991,'Salem's Lot,Stephen King,4.02,9780965772419,eng,405.0,1039,130,Doubleday,1975
4992,A Mad People's History of Madness,Dale Peterson,4.33,9780822953319,eng,384.0,9,0,University of Pittsburgh Press,1982
4993,A Christmas Carol (Great Illustrated Classics),Malvina G. Vogel,4.36,9781596792371,eng,238.0,466,31,Abdo Publishing Company,2005
4995,The Complete Works,Michel de Montaigne,4.44,9781400040216,eng,1392.0,166,13,Everyman's Library,2003
4999,The Avignon Quintet: Monsieur Livia Constanc...,Lawrence Durrell,4.07,9780571225552,en-US,1376.0,287,23,Faber & Faber,2004

In [22]:
num_high_rated_books = len(high_rated_books)

In [23]:
print(f'the number of books with an average rating gretaer than 4 is:{num_high_rated_books}')

the number of books with an average rating gretaer than 4 is:2115

In [24]:
df[(df['average_rating']>4.5) & (df['ratings_count']<10)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
63,鋼之鍊金術師 9,Hiromu Arakawa,4.57,9789861156521,NaN,184.0,4,0,東立,2004
178,鋼之鍊金術師 6,Hiromu Arakawa,4.58,9789861146140,NaN,191.0,5,0,東立,2004
224,Stargirl LitPlans on CD,Mary B. Collins,4.86,9781583372920,eng,210.0,5,0,Teacher's Pet Publications,2005
454,Literature Circle Guide: Bridge to Terabithia:...,Tara MacCarthy,5.00,9780439271714,eng,32.0,4,1,Teaching Resources,2002
584,Falling Angels (Luc Actar #1),Melissa M. Garcia,4.67,9780595377107,eng,216.0,1,0,iUniverse,2006
681,Fanning the Flame: Bible Cross and Mission,Chris Green,5.00,9780310249870,eng,336.0,1,1,Zondervan,2003
696,Tyrannosaurus Wrecks (Stanley #1),Laura Driscoll,5.00,9780786845033,eng,24.0,2,1,Disney Press,2003
741,The John Deere Two-Cylinder Tractor Encycloped...,Don Macmillan,4.75,9780760329634,eng,256.0,4,0,Voyageur Press,2007
757,The American Campaign: U.S. Presidential Campa...,James E. Campbell,5.00,9780890969403,eng,314.0,0,0,Texas A&M University Press,2000
1837,The Goon Show Volume 4: My Knees Have Fallen ...,NOT A BOOK,5.00,9780563388692,eng,2.0,3,0,BBC Physical Audio,1996
1856,鋼之鍊金術師 10,Hiromu Arakawa,4.60,9789861156538,NaN,188.0,3,0,東立,2005
1960,Wissenschaft der Logik: Die Lehre Vom Begriff ...,Georg Wilhelm Friedrich Hegel,4.78,9783787307678,ger,337.0,0,0,F. Meiner,1994
2244,Getting a Grip on the Basics: Building a Firm ...,Beth A. Jones,4.67,9781577948261,eng,124.0,9,0,Harrison House,2006
2496,Come Away My Beloved,Frances J. Roberts,4.58,9781593109158,eng,192.0,8,0,Barbour Books,2005
3178,Organizational Architecture: Designs for Chang...,David A. Nadler,4.62,9781555424435,eng,304.0,2,0,Jossey-Bass,1992
3438,Bill Gates: Computer Legend (Famous Lives),Sara Barton-Wood,5.00,9780739844328,eng,48.0,0,0,Raintree,2001
3706,A Wife After God's Own Heart Growth and Study ...,Elizabeth George,4.69,9780736911689,eng,160.0,9,1,Harvest House Publishers,2004
3833,His Princess Devotional: A Royal Encounter Wit...,Sheri Rose Shepherd,5.00,9781590529621,eng,240.0,2,0,Multnomah,2007
3909,Little Big Book for God's Children,Alice Wong,4.88,9780941807555,en-US,352.0,8,0,Welcome Books,2001
3927,Colossians and Philemon: A Critical and Exeget...,R. McL. Wilson,5.00,9780567044716,eng,512.0,1,0,T&T Clark Int'l,2005
4108,Willem de Kooning: Late Paintings,Julie Sylvester,5.00,9783829602266,eng,83.0,1,0,Schirmer Mosel,2006
4415,Corvette,Jerry Burton,4.83,9780883631218,eng,320.0,6,1,Universe Publishing(NY),2006
4455,The Complete Theory Fun Factory: Music Theory ...,Ian Martin,5.00,9780851621814,eng,96.0,1,0,Boosey & Hawkes Inc,2004
4917,Taxation of Mineral Rents,Ross Garnaut,5.00,9780198284543,eng,350.0,1,0,Oxford University Press USA,1983
4933,Oliver Wendell Holmes in Paris: Medicine Theo...,William C. Dowling,5.00,9781584655800,eng,179.0,1,1,University Press of New England,2007

In [31]:
mean_ratings = df[df['language_code'] == 'eng'].groupby('language_code')['average_rating'].mean()
print(mean_ratings)

language_code
eng    3.931143
Name: average_rating, dtype: float64

In [32]:
df.iloc[0:5,0:4]

,title,author,average_rating,isbn13
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222
2,Breach of Promise,James Scott Bell,4.00,9780310243878
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066

In [33]:
df.loc[[1,4],['language_code', 'num_pages', 'ratings_count']]

  language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [38]:
df['num_pages'].mean()

341.0940205355345

In [40]:
df['num_pages'].median()

304.0

In [100]:
df[df['year'] > 2009].shape[0]

5000

In [116]:
df = pd.read_csv('books.csv')
df[df['year']==2010].shape[0]

15

In [50]:
selected_books = df[(df['publisher'] == 'DAW') & (df['average_rating'] > 4)]

In [52]:
selected_books

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
71,By the Sword (Valdemar),Mercedes Lackey,4.25,9780886774639,eng,492.0,18531,249,DAW,2010
871,Storm Rising (Valdemar: Mage Storms #2),Mercedes Lackey,4.02,9780886777128,en-US,412.0,10781,86,DAW,2010
1523,Phoenix and Ashes (Elemental Masters #3),Mercedes Lackey,4.01,9780756402723,eng,480.0,6980,229,DAW,2010
1583,To Battle the Gods (Jalav Amazon Warrior #5),Sharon Green,4.07,9780886771287,eng,446.0,87,1,DAW,2010
3726,Oathblood (Valdemar: Vows and Honor #3),Mercedes Lackey,4.06,9780886777739,en-GB,394.0,9786,103,DAW,2010
4367,Joust (Dragon Jousters #1),Mercedes Lackey,4.02,9780756401535,eng,448.0,10113,263,DAW,2010

In [96]:
selected_books['author'].nunique

<bound method IndexOpsMixin.nunique of 0                Victor Hugo
12              Ray Bradbury
13       James H. Billington
16            John Steinbeck
17                Lyle Saxon
                ...
4963        Michael Connelly
4965    Doris Kearns Goodwin
4989           Peter Ackroyd
4995     Michel de Montaigne
4999        Lawrence Durrell
Name: author, Length: 772, dtype: object>

How many books with more than 500 pages were published after 2010?

In [117]:
df = pd.read_csv('books.csv')
df[(df['num_pages'] > 500) & (df['year'] >2010)].shape[0]

5

In [99]:
df[df['author'] == 'Agatha Christie'].shape[0]

21

In [112]:
df[(df['language_code'] == 'spa') & (df['year'] > 2000)].shape[0]

97

In [108]:
a = df[(df['average_rating']>4) &
       (df['publisher']=='DAW')] 
pd.unique(a['author'])

array(['Mercedes Lackey', 'Sharon Green'], dtype=object)

In [114]:
df = pd.read_csv('books.csv')

In [115]:
(df[(df['year']>2010) & 
    (df['num_pages']>500)]).shape[0]

5

In [118]:
c = df[df['year']>2000 ]
c.groupby('language_code').count()

,title,author,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,publisher,year
language_code,,,,,,,,,
en-GB,70,70,70,70,69,70,70,70,70
en-US,451,451,451,451,446,451,451,451,451
eng,2476,2476,2476,2476,2456,2476,2476,2476,2476
ger,28,28,28,28,28,28,28,28,28
jpn,13,13,13,13,13,13,13,13,13
lat,1,1,1,1,1,1,1,1,1
mul,2,2,2,2,2,2,2,2,2
spa,84,84,84,84,83,84,84,84,84